*****************************************************************************************************************
*   FILENAME    *    PRIORITY    *  TEST-CASE LENGTH  *  NUMBER OF ACTIONS  *    BUG PRODUCED  *  EXCEPTION
*****************************************************************************************************************
* Readme  *      HIGH      *         4         *       0         *       True     *  test-case failed to execute with following message: b'  File "Readme", line 1\r\n    This empty-file is needed to run AGTGAdriver.press_keycode(3) \r\n         ^\r\nSyntaxError: invalid syntax\r\n'
_________________________________________________________________________________________________________________
* TestCase00.py  *      HIGH      *         37         *       9         *       True     *  test-case failed to execute with following message: b'Traceback (most recent call last):\r\n  File "TestCase00.py", line 13, in <module>\r\n    el.click()\r\nAttributeError: \'NoneType\' object has no attribute \'click\'\r\n'
_________________________________________________________________________________________________________________
* TestCase01.py  *       LOW      *         37         *       9         *       False     *  Server-side error occurred. Please rerun this test-case
_________________________________________________________________________________________________________________
* TestCase02.py  *      HIGH      *         85         *       25         *       True     *  test-case failed to execute with following message: b'Traceback (most recent call last):\r\n  File "TestCase02.py", line 13, in <module>\r\n    el.click()\r\nAttributeError: \'NoneType\' object has no attribute \'click\'\r\n'
_________________________________________________________________________________________________________________
* TestCase03.py  *       LOW      *         43         *       11         *       False     *  Server-side error occurred. Please rerun this test-case
_________________________________________________________________________________________________________________
* TestCase04.py  *      HIGH      *         25         *       5         *       True     *  test-case failed to execute with following message: b'Traceback (most recent call last):\r\n  File "TestCase04.py", line 19, in <module>\r\n    el.click()\r\nAttributeError: \'NoneType\' object has no attribute \'click\'\r\n'
_________________________________________________________________________________________________________________
* TestCase05.py  *       LOW      *         31         *       7         *       False     *  Server-side error occurred. Please rerun this test-case
_________________________________________________________________________________________________________________
* TestCase06.py  *       LOW      *         19         *       3         *       False     *  None
_________________________________________________________________________________________________________________
* TestCase07.py  *      HIGH      *         64         *       18         *       True     *  test-case failed to execute with following message: b'Traceback (most recent call last):\r\n  File "TestCase07.py", line 13, in <module>\r\n    el.click()\r\nAttributeError: \'NoneType\' object has no attribute \'click\'\r\n'
_________________________________________________________________________________________________________________
* TestCase08.py  *      HIGH      *         59         *       17         *       True     *  test-case failed to execute with following message: b'Traceback (most recent call last):\r\n  File "TestCase08.py", line 15, in <module>\r\n    el = ElementFinder(driver, 32,497) \r\n  File "F:\\AGTGA\\TestSuite\\TestSuiteHelper.py", line 7, in ElementFinder\r\n    if x == el.location["x"] and y == el.location["y"]:\r\n  File "C:\\Users\\sakog\\AppData\\Local\\Programs\\Python\\Python38-32\\lib\\site-packages\\selenium\\webdriver\\remote\\webelement.py", line 534, in location\r\n    old_loc = self._execute(Command.GET_ELEMENT_LOCATION)[\'value\']\r\n  File "C:\\Users\\sakog\\AppData\\Local\\Programs\\Python\\Python38-32\\lib\\site-packages\\selenium\\webdriver\\remote\\webelement.py", line 633, in _execute\r\n    return self._parent.execute(command, params)\r\n  File "C:\\Users\\sakog\\AppData\\Local\\Programs\\Python\\Python38-32\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py", line 321, in execute\r\n    self.error_handler.check_response(response)\r\n  File "C:\\Users\\sakog\\AppData\\Local\\Programs\\Python\\Python38-32\\lib\\site-packages\\appium\\webdriver\\errorhandler.py", line 29, in check_response\r\n    raise wde\r\n  File "C:\\Users\\sakog\\AppData\\Local\\Programs\\Python\\Python38-32\\lib\\site-packages\\appium\\webdriver\\errorhandler.py", line 24, in check_response\r\n    super(MobileErrorHandler, self).check_response(response)\r\n  File "C:\\Users\\sakog\\AppData\\Local\\Programs\\Python\\Python38-32\\lib\\site-packages\\selenium\\webdriver\\remote\\errorhandler.py", line 242, in check_response\r\n    raise exception_class(message, screen, stacktrace)\r\nselenium.common.exceptions.StaleElementReferenceException: Message: Cached elements \'By.clazz: android.widget.Button\' do not exist in DOM anymore\r\n\r\n'
_________________________________________________________________________________________________________________
* TestCase09.py  *       LOW      *         10         *       0         *       False     *  None
_________________________________________________________________________________________________________________
*   Average Test-Case Length               =                         44.44444444444444
*   Average Action per Test-case           =                         11.555555555555555
*****************************************************************************************************************