*****************************************************************************************************************
*   FILENAME    *    PRIORITY    *  TEST-CASE LENGTH  *  NUMBER OF ACTIONS  *    BUG PRODUCED  *  EXCEPTION
*****************************************************************************************************************
* Readme  *      HIGH      *         4         *       0         *       True     *  test-case failed to execute with following message: b'  File "Readme", line 1\r\n    This empty-file is needed to run AGTGAdriver.press_keycode(3) \r\n         ^\r\nSyntaxError: invalid syntax\r\n'
_________________________________________________________________________________________________________________
* TestCase00.py  *      HIGH      *         95         *       27         *       True     *  test-case failed to execute with following message: b'Traceback (most recent call last):\r\n  File "TestCase00.py", line 13, in <module>\r\n    el.click()\r\nAttributeError: \'NoneType\' object has no attribute \'click\'\r\n'
_________________________________________________________________________________________________________________
* TestCase01.py  *      HIGH      *         23         *       3         *       True     *  test-case failed to execute with following message: b'Traceback (most recent call last):\r\n  File "TestCase01.py", line 13, in <module>\r\n    el.click()\r\nAttributeError: \'NoneType\' object has no attribute \'click\'\r\n'
_________________________________________________________________________________________________________________
* TestCase02.py  *       LOW      *         23         *       3         *       False     *  Server-side error occurred. Please rerun this test-case
_________________________________________________________________________________________________________________
* TestCase03.py  *       LOW      *         20         *       2         *       False     *  Server-side error occurred. Please rerun this test-case
_________________________________________________________________________________________________________________
* TestCase04.py  *      HIGH      *         26         *       4         *       True     *  test-case failed to execute with following message: b'Traceback (most recent call last):\r\n  File "TestCase04.py", line 22, in <module>\r\n    el.click()\r\nAttributeError: \'NoneType\' object has no attribute \'click\'\r\n'
_________________________________________________________________________________________________________________
* TestCase05.py  *      HIGH      *         32         *       6         *       True     *  test-case failed to execute with following message: b'Traceback (most recent call last):\r\n  File "TestCase05.py", line 13, in <module>\r\n    el.click()\r\nAttributeError: \'NoneType\' object has no attribute \'click\'\r\n'
_________________________________________________________________________________________________________________
* TestCase06.py  *      HIGH      *         29         *       5         *       True     *  test-case failed to execute with following message: b'Traceback (most recent call last):\r\n  File "TestCase06.py", line 8, in <module>\r\n    driver = webdriver.Remote(command_executor=port, desired_capabilities={\'automationName\' : \'UiAutomator2\',\'deviceName\': \'samsung SM-G390F\',\'platformName\': \'Android\',  \'app\': \'F:/AGTGA/APKS/calm.apk\' , \'autoGrantPermissions\' : \'true\', \'appWaitActivity\' : \'*.*\',\'fullreset\' : \'false\',\'noReset\' : \'true\' } ) \r\n  File "C:\\Users\\sakog\\AppData\\Local\\Programs\\Python\\Python38-32\\lib\\site-packages\\appium\\webdriver\\webdriver.py", line 147, in __init__\r\n    super(WebDriver, self).__init__(\r\n  File "C:\\Users\\sakog\\AppData\\Local\\Programs\\Python\\Python38-32\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py", line 157, in __init__\r\n    self.start_session(capabilities, browser_profile)\r\n  File "C:\\Users\\sakog\\AppData\\Local\\Programs\\Python\\Python38-32\\lib\\site-packages\\appium\\webdriver\\webdriver.py", line 227, in start_session\r\n    response = self.execute(RemoteCommand.NEW_SESSION, parameters)\r\n  File "C:\\Users\\sakog\\AppData\\Local\\Programs\\Python\\Python38-32\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py", line 321, in execute\r\n    self.error_handler.check_response(response)\r\n  File "C:\\Users\\sakog\\AppData\\Local\\Programs\\Python\\Python38-32\\lib\\site-packages\\selenium\\webdriver\\remote\\errorhandler.py", line 242, in check_response\r\n    raise exception_class(message, screen, stacktrace)\r\nselenium.common.exceptions.WebDriverException: Message: An unknown server-side error occurred while processing the command. Original error: Cannot start the \'com.calm.android\' application. Visit https://github.com/appium/appium/blob/master/docs/en/writing-running-appium/android/activity-startup.md for troubleshooting. Original error: Error executing adbExec. Original error: \'Command \'C:\\\\Windows.old\\\\Users\\\\sakog\\\\AppData\\\\Local\\\\Android\\\\Sdk\\\\platform-tools\\\\adb.exe -P 5037 -s 42003eb3e4d785cf shell am start -W -n com.calm.android/com.calm.android.ui.misc.SplashActivity -S\' timed out after 20000ms\'. Try to increase the 20000ms adb execution timeout represented by \'adbExecTimeout\' capability\r\n\r\n'
_________________________________________________________________________________________________________________
* TestCase07.py  *      HIGH      *         38         *       8         *       True     *  test-case failed to execute with following message: b'Traceback (most recent call last):\r\n  File "TestCase07.py", line 13, in <module>\r\n    el.click()\r\nAttributeError: \'NoneType\' object has no attribute \'click\'\r\n'
_________________________________________________________________________________________________________________
* TestCase08.py  *      HIGH      *         20         *       2         *       True     *  test-case failed to execute with following message: b'Traceback (most recent call last):\r\n  File "TestCase08.py", line 13, in <module>\r\n    el.click()\r\nAttributeError: \'NoneType\' object has no attribute \'click\'\r\n'
_________________________________________________________________________________________________________________
* TestCase09.py  *       LOW      *         41         *       9         *       False     *  Server-side error occurred. Please rerun this test-case
_________________________________________________________________________________________________________________
* TestCase10.py  *       LOW      *         29         *       5         *       False     *  Server-side error occurred. Please rerun this test-case
_________________________________________________________________________________________________________________
* TestCase11.py  *      HIGH      *         23         *       3         *       True     *  test-case failed to execute with following message: b'Traceback (most recent call last):\r\n  File "TestCase11.py", line 13, in <module>\r\n    el.click()\r\nAttributeError: \'NoneType\' object has no attribute \'click\'\r\n'
_________________________________________________________________________________________________________________
*   Average Test-Case Length               =                         33.25
*   Average Action per Test-case           =                         6.416666666666667
*****************************************************************************************************************