*****************************************************************************************************************
*   FILENAME    *    PRIORITY    *  TEST-CASE LENGTH  *  NUMBER OF ACTIONS  *    BUG PRODUCED  *  EXCEPTION
*****************************************************************************************************************
* Readme  *      HIGH      *         1         *       0         *       True     *  test-case failed to execute with following message: b'  File "Readme", line 1\r\n    This empty-file is needed to run AGTGAdriver.press_keycode(3) \r\n             ^\r\nSyntaxError: invalid syntax\r\n'
_________________________________________________________________________________________________________________
* TestCase00.py  *       LOW      *         19         *       3         *       False     *  None
_________________________________________________________________________________________________________________
* TestCase01.py  *       LOW      *         16         *       2         *       False     *  Server-side error occurred. Please rerun this test-case
_________________________________________________________________________________________________________________
* TestCase02.py  *       LOW      *         13         *       1         *       False     *  None
_________________________________________________________________________________________________________________
* TestCase03.py  *       LOW      *         16         *       2         *       False     *  None
_________________________________________________________________________________________________________________
* TestCase04.py  *       LOW      *         41         *       11         *       False     *  None
_________________________________________________________________________________________________________________
* TestCase05.py  *       LOW      *         34         *       8         *       False     *  None
_________________________________________________________________________________________________________________
* TestCase06.py  *       LOW      *         16         *       2         *       False     *  None
_________________________________________________________________________________________________________________
* TestCase07.py  *       LOW      *         34         *       8         *       False     *  None
_________________________________________________________________________________________________________________
* TestCase08.py  *      HIGH      *         16         *       2         *       True     *  test-case failed to execute with following message: b'Traceback (most recent call last):\r\n  File "TestCase08.py", line 16, in <module>\r\n    el.click()\r\nAttributeError: \'NoneType\' object has no attribute \'click\'\r\n'
_________________________________________________________________________________________________________________
* TestCase09.py  *       LOW      *         19         *       3         *       False     *  None
_________________________________________________________________________________________________________________
* TestCase10.py  *       LOW      *         13         *       1         *       False     *  None
_________________________________________________________________________________________________________________
* TestCase11.py  *       LOW      *         20         *       4         *       False     *  None
_________________________________________________________________________________________________________________
* TestCase12.py  *       LOW      *         22         *       4         *       False     *  None
_________________________________________________________________________________________________________________
* TestCase13.py  *       LOW      *         14         *       2         *       False     *  None
_________________________________________________________________________________________________________________
* TestCase14.py  *       LOW      *         22         *       4         *       False     *  None
_________________________________________________________________________________________________________________
* TestCase15.py  *      HIGH      *         67         *       19         *       True     *  test-case failed to execute with following message: b'Traceback (most recent call last):\r\n  File "TestCase15.py", line 25, in <module>\r\n    el.click()\r\nAttributeError: \'NoneType\' object has no attribute \'click\'\r\n'
_________________________________________________________________________________________________________________
* TestCase16.py  *      MEDIUM      *         64         *       18         *       False     *  Server-side error occurred. Please rerun this test-case
_________________________________________________________________________________________________________________
*   Average Test-Case Length               =                         34.2
*   Average Action per Test-case           =                         8.2
*****************************************************************************************************************